#!/bin/bash
# Deployment script for EcoSphere AI

echo "🚀 EcoSphere AI - Deployment Guide"
echo "===================================="
echo ""
echo "Step 1: Create GitHub Repository"
echo "  - Go to: https://github.com/new"
echo "  - Repo name: ecosphere-ai"
echo "  - Make it PUBLIC"
echo "  - Click 'Create repository'"
echo ""
echo "Step 2: Run these commands (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "  git remote add origin https://github.com/YOUR_USERNAME/ecosphere-ai.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "Step 3: Deploy to Streamlit Cloud"
echo "  - Go to: https://share.streamlit.io"
echo "  - Click 'New app'"
echo "  - Select your GitHub repo: YOUR_USERNAME/ecosphere-ai"
echo "  - Main file: app.py"
echo "  - Click 'Deploy'"
echo ""
echo "Your app will be live at: https://ecosphere-ai-<random>.streamlit.app"
echo ""
